name: Caiquemorais
version: 1.0
main: org.caique.caiquemorais.Caiquemorais
api-version: 1.20
commands:
  login:
    description: Faz login no servidor
    usage: /login <senha>
  register:
    description: Registra-se no servidor
    usage: /register <senha> <confirmação>
  g:
    description: Fala no chat global
    usage: /g <mensagem>
  tags:
    description: Gerencia tags
    usage: /tags [tag]
  vipinfo:
    description: Mostra informações do VIP
    usage: /vipinfo
  punir:
    description: Pune um jogador
    usage: /punir <jogador> [motivo] [link da prova]
  desbanir:
    description: Desbane um jogador
    usage: /desbanir <jogador>
  checkpunir:
    description: Verifica as punições de um jogador
    usage: /checkpunir <jogador>
  lobby:
    description: Troca de lobby
    usage: /lobby <lobby>
permissions:
  caiquemorais.punish:
    description: Permite usar o comando /punir
    default: op
  caiquemorais.unban:
    description: Permite usar o comando /desbanir
    default: op
  caiquemorais.checkpunish:
    description: Permite usar o comando /checkpunir
    default: op